# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm i
            - npm run dc:build
            
            # use the pipe to push to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.1.1
              variables:
                IMAGE_NAME: backend-micro-{{projectName}}
                TAGS: '${BITBUCKET_BUILD_NUMBER} latest'
